import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';

/**
 * Creates a valid demo PDF with real content using pdf-lib.
 * This is used for mock downloads until a real backend is connected.
 */
export async function createDemoPdf(title: string, subtitle: string): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4

  const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const { width, height } = page.getSize();

  // Title
  page.drawText(title, {
    x: 50,
    y: height - 80,
    size: 28,
    font: helveticaBold,
    color: rgb(0.12, 0.23, 0.54), // Docabot brand blue
  });

  // Subtitle
  page.drawText(subtitle, {
    x: 50,
    y: height - 120,
    size: 14,
    font: helvetica,
    color: rgb(0.3, 0.3, 0.3),
  });

  // Separator line
  page.drawLine({
    start: { x: 50, y: height - 140 },
    end: { x: width - 50, y: height - 140 },
    thickness: 1,
    color: rgb(0.8, 0.8, 0.8),
  });

  // Body text
  const bodyLines = [
    'This PDF was generated by Docabot — your smart document toolkit.',
    '',
    'Docabot provides tools to merge, compress, convert, split and',
    'manage your PDF files quickly and easily.',
    '',
    'This is a demo document. When connected to a real backend,',
    'the actual processed PDF will be downloaded instead.',
    '',
    `Generated on: ${new Date().toLocaleString()}`,
  ];

  let y = height - 180;
  for (const line of bodyLines) {
    page.drawText(line, {
      x: 50,
      y,
      size: 12,
      font: helvetica,
      color: rgb(0.15, 0.15, 0.15),
    });
    y -= 22;
  }

  // Footer
  page.drawText('docabot.com — Simple PDF Tools. One Place.', {
    x: 50,
    y: 40,
    size: 10,
    font: helvetica,
    color: rgb(0.5, 0.5, 0.5),
  });

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

/**
 * Triggers a browser download of the given bytes as a PDF file.
 */
export function downloadPdfBytes(pdfBytes: Uint8Array, filename: string) {
  const blob = new Blob([pdfBytes], { type: 'application/pdf' });
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}
